Feat/gcloud region
odenio/pgpool-cloudsql pull request #9
Opened 2023-08-02 12:56 UTC by atbore-phx

This PR allows to discover DBs worldwide and not only in the pod's region

2023-08-02 13:59 UTC, n-oden commented
Hey, thanks for the PR! I'll try to review this properly before the end of the week.

2023-08-02 14:51 UTC, n-oden requested changes
I think this is a reasonable thing to want as a feature, but it should probably not be the default, and definitely the default behavior should not change in a patch release.  

Please add a boolean helm configuration value `.discovery.stay_in_region` with the default being `true` so that the default behavior does not change, and make the discovery script construct the filters based on that value.

2023-08-02 14:51 UTC, n-oden commented on README.md
> +v1.1.0 | v1.1.1 | [link](UPGRADE.md#v110--v111)
Please add the 1.1.1 version on top of the 1.0.x version rather than deleting it

2023-08-02 14:51 UTC, n-oden commented on UPGRADE.md
> +## `v1.1.0` → `v1.1.1`
Please leave the 1.0.x -> 1.1.1 upgrade steps in place and put the 1.1.0 -> 1.1.1 upgrade instructions above it

2023-08-02 14:51 UTC, n-oden commented on bin/discovery.sh
> +      --filter "name~^${PRIMARY_INSTANCE_PREFIX} AND state:RUNNABLE AND instanceType:CLOUD_SQL_INSTANCE" \
this should be optional behavior; see longer comment above

2023-08-02 14:51 UTC, n-oden commented on UPGRADE.md
> +> 🛑 this release allows to discover databases instance worldwide inside your Project and not only in the pod region.
nit for grammar/usage: "this release allows discovering database instances worldwide inside your GCP project, and not only in the pod region"

2023-08-02 16:20 UTC, atbore-phx commented
> Please add a boolean helm configuration value .discovery.stay_in_region

Hi @n-oden,
Thanks for the fast reply,
Make this feature optional is the right way to proceed indeed.
Let me have a couple of days and it will be done 👍.

2023-08-04 07:55 UTC, atbore-phx commented
hi @n-oden, ready for review ;)

2023-08-09 17:11 UTC, n-oden requested changes
The logic mostly LGTM.  Just a few nits about documentation and style.

Also please address the failing lint test: you need to update the version number in Chart.yaml.

(Don't worry about the failing docker build test; that's unrelated to this PR.)

2023-08-09 17:11 UTC, n-oden commented on bin/discovery.sh
> +if [ "${STAY_IN_REGION:-}" = "false" ]; then
A tiny nit, but for consistency please put the default-handing code up in the block of variable declarations in L17-22:

```
STAY_IN_REGION="${STAY_IN_REGION:-"true"}"
```

And then here just say `if ["${STAY_IN_REGION}" = "false" ]...`

2023-08-09 17:11 UTC, n-oden commented on charts/pgpool-cloudsql/templates/deployment.yaml
> +          value: {{ .Values.discovery.stay_in_region }}
this needs to be quoted:

```
- name: STAY_IN_REGION
  value: {{ .Values.discovery.stayInRegion | quote }}
```

2023-08-09 17:11 UTC, n-oden commented on charts/pgpool-cloudsql/values.yaml
> +  stay_in_region: true
nit: for consistency here, please use camelCase: 

```
stayInRegion: true
```

2023-08-09 17:11 UTC, n-oden commented on UPGRADE.md
> +> 🛑 this release allows discovering database instances worldwide inside your GCP project, and not only in the pod region.
Please add a `### VALUES- new" section covering the new value option; see the v1.1.0 upgrade docs for an example.

Also, change the 🛑 emoji to an ℹ️ emoji, as the former is meant to denote breaking changes.

2023-08-10 07:29 UTC, atbore-phx commented
> The logic mostly LGTM. Just a few nits about documentation and style.
> 
> Also please address the failing lint test: you need to update the version number in Chart.yaml.
> 
> (Don't worry about the failing docker build test; that's unrelated to this PR.)

ready for review ;)

2023-08-10 17:02 UTC, n-oden approved these changes
Approved. I'm currently on an airplane but will try to get this merged and published tomorrow.

2023-08-11 17:09 UTC, merged

2023-08-11 17:19 UTC, n-oden commented
v1.1.1 is released! Thank you for the contribution!